### ISSUE TITLE
Uncertainty propagation (possible feature request)

### ISSUE THREAD

**Issue by ShuhuaGao** [willtebbutt/Stheno.jl#130]
Thanks for this excellent package. I am wondering whether it supports uncertainty propagation, that is,  when the inputs to GP themselves have uncertainty (e..g, being Guassian distributed). I did not find relevant information in the documentation. 

There are quite a few papers on this topic, like Agathe Girard's [PhD thesis](http://www.dcs.gla.ac.uk/~rod/publications/Gir04.pdf). This feature is particularly useful if we want to use GP for multi-step-ahead predictions, e.g., in a model predictive control context. The prediction at `t+2` depends the previous prediction at `t+1`.

**Comment by willtebbutt** [comment]
Hiya, glad you like the package.

There are currently no plans to support this type of functionality in this package, basically because it requires approximate inference and there are _lots_ of ways to approach it (e.g. linearisation, variational approximations, MCMC, etc). This package is more focused on jointly Gaussian problems, the intention being that one would compose this package with others to handle non-Gaussian things.

What _would_ be fantastic is if you wanted to create a separate package that provided various approaches to handling uncertainty in the inputs to GPs. We need a similar package for Deep GPs.

**Comment by ShuhuaGao** [comment]
Thank you for your reply @willtebbutt 👏 . Since I am not an expert in GP, I will read those related papers first in the near future and may create a package, as you suggested, if I can understand those mathematics well. In fact, such a function seems also missing in Python based GP packages. (There are indeed Python packages claiming the support but cannot work properly. 😭 )
