### ISSUE TITLE
Shared data for finite GP

### ISSUE THREAD

**Issue by pmcvay** [willtebbutt/Stheno.jl#132]
First, great job on the library. It is really cool.

You seem to be interested in how people use your library so I thought I would give one quick thought. I use it for bayesian optimization and the general procedure is to compute a gp, select a new point, compute a new gp, etc. This makes it slightly annoying that Stheno uses shared data when you pass the data to a gp. I show an example of that below. 

Also, I don't think the shared data has any real benefit as plotting the gp fails if you change the data and don't recompute the gp. Also, shown in the example. 

There is a simple solution to just add `copy(X_data)` to function call. But since I don't think it serves any purpose to use shared data, I thought I at least let you know my use case.

```julia 
X_data = rand(2) .* 10 .- 5
y_data = sin.(X_data)
f = GP(1. * Matern52(), GPC())
f_p = f | Obs(f(X_data), y_data)

push!(X_data, 1) # fails because of shared data
X_data[2] = -2 
plot(f_p(collect(-5:.02:5)), samples = 10, color = "blue") # fails since the gp didn't update 
```

**Comment by willtebbutt** [comment]
Ah interesting use-case! Glad to hear people are trying to use it for Bayesopt.

I guess I had been implicity assuming immutability throughout Stheno -- once data is passed into a GP, I wasn't expecting it to change.

> Also, I don't think the shared data has any real benefit as plotting the gp fails if you change the data and don't recompute the gp. Also, shown in the example.

It's just a performance issue I guess 🤷 

I would very much prefer to keep Stheno's assumptions about immutability, so I think the best solution here is for Stheno to include some proper sequential conditioning functionality so that you don't have to think about mutating your inputs. We've already got this in [`AbstractGPs.jl`](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/df2d3b22be3827da04cff5970ce6c5268c9866a2/src/posterior_gp/posterior_gp.jl#L38) (not tested for performance yet though) and I'm going to be moving Stheno over to use `AbstractGPs` so I'm hoping to get that functionality for free in Stheno (no promises on the timeline for that though).

A good solution in the mean time is, as you say, either to copy the data or to just to construct a new posterior object whenever you modify your data.
